version: '3.7'
services:
  db:
    image: postgres:11.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    environment:
      DATABASE_URL:
    build:
      args:
        BUNDLER_OPTS: --jobs=5
        RAILS_ENVIRONMENT: development
    command: bash -c "rm -f tmp/pids/server.pid && dumb-init bundle exec puma -C config/puma.rb"
    depends_on:
      - db
